export var AppKey : any = 'vtexappkey-paulette-NGKZXP'
export var AppToken : any  = 'UVVRFSHDNGSWQCAPXAASKGUTDEHZEBXODVBZWRAQOTPJFLBZRGPDFCPNBBNBKIYLJDTUABTGZKDRRKOSCHHYLTIAFNXUDZFGUDABRHYQNIEVYYWQMUYCAAZPUTONDYDA'
